# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/New Volume/School/2026_Spring/SENG499/SimVital"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/New Volume/School/2026_Spring/SENG499/SimVital"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/New Volume/School/2026_Spring/SENG499/SimVital/CMakeFiles" "/mnt/New Volume/School/2026_Spring/SENG499/SimVital//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/New Volume/School/2026_Spring/SENG499/SimVital/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimVital

# Build rule for target.
SimVital: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimVital
.PHONY : SimVital

# fast build rule for target.
SimVital/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/build
.PHONY : SimVital/fast

#=============================================================================
# Target rules for targets named SimVital_autogen_timestamp_deps

# Build rule for target.
SimVital_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimVital_autogen_timestamp_deps
.PHONY : SimVital_autogen_timestamp_deps

# fast build rule for target.
SimVital_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital_autogen_timestamp_deps.dir/build.make CMakeFiles/SimVital_autogen_timestamp_deps.dir/build
.PHONY : SimVital_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SimVital_autogen

# Build rule for target.
SimVital_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimVital_autogen
.PHONY : SimVital_autogen

# fast build rule for target.
SimVital_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital_autogen.dir/build.make CMakeFiles/SimVital_autogen.dir/build
.PHONY : SimVital_autogen/fast

SimVital_autogen/mocs_compilation.o: SimVital_autogen/mocs_compilation.cpp.o
.PHONY : SimVital_autogen/mocs_compilation.o

# target to build an object file
SimVital_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/SimVital_autogen/mocs_compilation.cpp.o
.PHONY : SimVital_autogen/mocs_compilation.cpp.o

SimVital_autogen/mocs_compilation.i: SimVital_autogen/mocs_compilation.cpp.i
.PHONY : SimVital_autogen/mocs_compilation.i

# target to preprocess a source file
SimVital_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/SimVital_autogen/mocs_compilation.cpp.i
.PHONY : SimVital_autogen/mocs_compilation.cpp.i

SimVital_autogen/mocs_compilation.s: SimVital_autogen/mocs_compilation.cpp.s
.PHONY : SimVital_autogen/mocs_compilation.s

# target to generate assembly for a file
SimVital_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/SimVital_autogen/mocs_compilation.cpp.s
.PHONY : SimVital_autogen/mocs_compilation.cpp.s

app/main.o: app/main.cpp.o
.PHONY : app/main.o

# target to build an object file
app/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/app/main.cpp.o
.PHONY : app/main.cpp.o

app/main.i: app/main.cpp.i
.PHONY : app/main.i

# target to preprocess a source file
app/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/app/main.cpp.i
.PHONY : app/main.cpp.i

app/main.s: app/main.cpp.s
.PHONY : app/main.s

# target to generate assembly for a file
app/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/app/main.cpp.s
.PHONY : app/main.cpp.s

core/src/MitBihParser.o: core/src/MitBihParser.cpp.o
.PHONY : core/src/MitBihParser.o

# target to build an object file
core/src/MitBihParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/core/src/MitBihParser.cpp.o
.PHONY : core/src/MitBihParser.cpp.o

core/src/MitBihParser.i: core/src/MitBihParser.cpp.i
.PHONY : core/src/MitBihParser.i

# target to preprocess a source file
core/src/MitBihParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/core/src/MitBihParser.cpp.i
.PHONY : core/src/MitBihParser.cpp.i

core/src/MitBihParser.s: core/src/MitBihParser.cpp.s
.PHONY : core/src/MitBihParser.s

# target to generate assembly for a file
core/src/MitBihParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/core/src/MitBihParser.cpp.s
.PHONY : core/src/MitBihParser.cpp.s

core/src/RingBuffer.o: core/src/RingBuffer.cpp.o
.PHONY : core/src/RingBuffer.o

# target to build an object file
core/src/RingBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/core/src/RingBuffer.cpp.o
.PHONY : core/src/RingBuffer.cpp.o

core/src/RingBuffer.i: core/src/RingBuffer.cpp.i
.PHONY : core/src/RingBuffer.i

# target to preprocess a source file
core/src/RingBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/core/src/RingBuffer.cpp.i
.PHONY : core/src/RingBuffer.cpp.i

core/src/RingBuffer.s: core/src/RingBuffer.cpp.s
.PHONY : core/src/RingBuffer.s

# target to generate assembly for a file
core/src/RingBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimVital.dir/build.make CMakeFiles/SimVital.dir/core/src/RingBuffer.cpp.s
.PHONY : core/src/RingBuffer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SimVital_autogen"
	@echo "... SimVital_autogen_timestamp_deps"
	@echo "... SimVital"
	@echo "... SimVital_autogen/mocs_compilation.o"
	@echo "... SimVital_autogen/mocs_compilation.i"
	@echo "... SimVital_autogen/mocs_compilation.s"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... core/src/MitBihParser.o"
	@echo "... core/src/MitBihParser.i"
	@echo "... core/src/MitBihParser.s"
	@echo "... core/src/RingBuffer.o"
	@echo "... core/src/RingBuffer.i"
	@echo "... core/src/RingBuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

